### ISSUE TITLE
Bit-vector statistics: GAP (compressed blocks)=0, BIT (uncompressed blocks)=0

### ISSUE THREAD

**Issue by Malfoy** [tlk00/BitMagic#59]
I have a weird behavior of a bm::bvector<> that appears from a given size.
The bitvector if full of 1 from 0 to 16.7 million.
I expect that a call to select on bm::bvector<>::rs_index_type to be the identity (x->x)
But this is not the case from a given size of the bitvector.
With 15 million, everything works correctly, but not with 16.7 million.
Interestingly when I plot the calc_stat function I have 
Bit-vector statistics: GAP (compressed blocks)=1, BIT (uncompressed blocks)=0
for the 15 million dataset and
Bit-vector statistics: GAP (compressed blocks)=0, BIT (uncompressed blocks)=0
For the 16.7 million

Is this expected?
I tried to use the latest release and the actual codebase for the same result.

**Comment by tlk00** [comment]
GAP (compressed blocks)=0, BIT (uncompressed blocks)=0 could be because all 1 blocks gets stored as a special pointer so it is not GAP or BIT (special block type), no memory consumption for that.

Can I ask for a simple code sample to debug select?
If it is hard to generate the vector please share a serialized BLOB somewhere.

**Comment by tlk00** [comment]
Thank you for the inside with the calc_stat() function.
Looks like i found the issue. Working on a fix.

**Comment by tlk00** [comment]
Fix for bvector<>::select() committed to the master codebase, please try.
